name: bintango_jp
description: Flash card application of Japanese language for Indonesian

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+10

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  ## Google API package
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  google_mobile_ads: ^1.1.0

  ## basic packages
  auto_size_text:
  flutter_svg: ^1.0.3
  flutter_gen:
  fluttertoast: ^8.0.8
  flutter_riverpod: ^1.0.3
  dio:
  logger:
  flutter_secure_storage:
  intl:
  shimmer:
  package_info: ^2.0.2
  shared_preferences: ^2.0.13

  ## Firebase packages
  firebase_core:
  firebase_crashlytics: ^2.5.3
  firebase_messaging: ^11.2.8
  firebase_analytics: ^9.1.2

  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.3
  flutter_inappwebview:
  floor: ^1.2.0
  collection:
  flutter_tts: ^3.3.3
  flutter_switch: ^0.3.2
  material_floating_search_bar: ^0.3.6
  app_tracking_transparency: ^2.0.2+1
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^7.3.0
  flutter_countdown_timer: ^4.1.0
  in_app_review: ^2.0.4
  flutter_dialogs: ^2.1.1
  social_share: ^2.2.1
  screenshot: ^1.2.3
  path_provider:
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  floor_generator: ^1.2.0
  pedantic_mono:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/lottie/
    - assets/svg/
    - assets/png/
    - assets/dot/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
